### PR TITLE
ci: add github action for building firmware

### PR DESCRIPTION
**Pull request by cfriedt**
2 commits
* uncomment declaration of `phy_bbpll_en_usb()`
* add github action for building firmware

Working:
https://github.com/cfriedt/ICE-V-Wireless/runs/7683278820

### CODE REVIEW

**Comment by emeb** [comment]
Just to clarify - which version of ESP-IDF did you need to build successfully?

**Comment by cfriedt** [comment]
> Just to clarify - which version of ESP-IDF did you need to build successfully?

v4.4

**Comment by emeb** [comment]
I've reverted HEAD to the commit prior to when the exclusive V5.0 changes were added and I was able to build with IDF V4.4.2 stable without needing to uncomment the declaration of the phy_bbpll_en_usb(bool en) function. It appears that they added that somewhere between 4.4.1 and 4.4.2. To make your PR immune to IDF version changes, please add the following around that declaration:

#include "esp_idf_version.h"

#if ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(4, 4, 2)
// there's an include for this but it doesn't define the function
// if it doesn't think it needs it, so manually declare the function
extern void phy_bbpll_en_usb(bool en);
#endif

**Comment by cfriedt** [comment]
@emeb - Done!

https://github.com/cfriedt/ICE-V-Wireless/runs/7692707910

**Pull request merged**
